## Unit-3 Feature Creation & Feature Transformation

In [1]:
import pandas as pd
import numpy as np
data = {
    'A':[10,12,12,15,14],
    'B':[3,4,7,1,6]
}
df = pd.DataFrame(data)
df

    A  B
0  10  3
1  12  4
2  12  7
3  15  1
4  14  6

In [2]:
df['C'] = df['A'] + df['B']
df

    A  B   C
0  10  3  13
1  12  4  16
2  12  7  19
3  15  1  16
4  14  6  20

In [3]:
df['D'] = df['C'] + 4

In [5]:
df

    A  B   C   D
0  10  3  13  17
1  12  4  16  20
2  12  7  19  23
3  15  1  16  20
4  14  6  20  24

In [7]:
df['Result'] = np.where(df['D']>18,'Pass','Fail')
df

    A  B   C   D Result
0  10  3  13  17   Fail
1  12  4  16  20   Pass
2  12  7  19  23   Pass
3  15  1  16  20   Pass
4  14  6  20  24   Pass

In [8]:
df['Grade'] = np.where(df['D']>22,'A',
                       np.where(df['D']>19,'B',
                                np.where(df['D']>17,'C','D')))
df

    A  B   C   D Result Grade
0  10  3  13  17   Fail     D
1  12  4  16  20   Pass     B
2  12  7  19  23   Pass     A
3  15  1  16  20   Pass     B
4  14  6  20  24   Pass     A

In [11]:
data = {
    'Marks':[20,21,23,24,25,24,20,21,24,25,24,22],
    'Gender':['Male','Female','Male','Female','Male','Female',
             'Male','Female','Male','Female','Male','Female']
}
df=pd.DataFrame(data)
df

    Marks  Gender
0      20    Male
1      21  Female
2      23    Male
3      24  Female
4      25    Male
5      24  Female
6      20    Male
7      21  Female
8      24    Male
9      25  Female
10     24    Male
11     22  Female

## One-Hot Encoding

In [13]:
df = pd.get_dummies(df,drop_first=True)
df

    Marks  Gender_Male
0      20            1
1      21            0
2      23            1
3      24            0
4      25            1
5      24            0
6      20            1
7      21            0
8      24            1
9      25            0
10     24            1
11     22            0

## Train-Validation Split

In [54]:
x = df['Gender_Male']
y = df['Marks']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,
                                                 random_state=10)
x_train

5     0
11    0
8     1
10    1
3     0
1     0
0     1
4     1
9     0
Name: Gender_Male, dtype: uint8